# Site settings
title: U-QASAR Methodology WebBook
email: hello@uqasar.eu
description: > # this means to ignore newlines until "baseurl:"
  The U-QASAR methodology webbook is a practice-oriented overview of a quality assurance,
  control and measurement methodology that has been developed in the project. The webbook
  provides background and practical guidelines on quality management of both the software de-
  velopment process and the software product itself.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://webbook.uqasar.eu" # the base hostname & protocol for your site
twitter_username: uqasar
github_username:  u-qasar

defaults:
    - scope:
        path: ""
      values:
        layout: flyer
# Build settings
markdown: kramdown
collections:
    part11:
        permalink: /section1/:collection/:title.html
        output: true
    part12:
        permalink: /section1/:collection/:title.html
        output: true
    part13:
        permalink: /section1/:collection/:title.html
        output: true    
    part14:
        permalink: /section1/:collection/:title.html
        output: true    
    part21:
        permalink: /section2/:collection/:title.html
        output: true    
    part22:
        permalink: /section2/:collection/:title.html
        output: true
    part24:
        permalink: /section2/:collection/:title.html
        output: true
    part31:
        permalink: /section3/:collection/:title.html
        output: true    
    part41:
        permalink: /section4/:collection/:title.html
        output: true    
    part42:
        permalink: /section4/:collection/:title.html
        output: true    
    part51:
        permalink: /section5/:collection/:title.html
        output: true  
    part52:
        permalink: /section5/:collection/:title.html
        output: true    
    part61:
        permalink: /section6/:collection/:title.html
        output: true 
    part62:
        permalink: /section6/:collection/:title.html
        output: true  
    part63:
        permalink: /section6/:collection/:title.html
        output: true  
    part64:
        permalink: /section6/:collection/:title.html
        output: true  
    part65:
        permalink: /section6/:collection/:title.html
        output: true  
    part66:
        permalink: /section6/:collection/:title.html
        output: true     

